version: 2
jobs:
  build:
    parallelism: 2
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.5.1-node-browsers
       - image: circleci/postgres:9.6.2
       - image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
       - image: redis
    working_directory: ~/acehelp
    environment:
      TZ: "/usr/share/zoneinfo/America/New_York"
      RAILS_ENV: "test"
      RACK_ENV: "test"
      KNAPSACK_GENERATE_REPORT: "true"

    steps:

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - gem-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          - gem-cache-{{ checksum "Gemfile.lock" }}
          - gem-cache

      # Enable if using yarn
      - restore_cache:
          keys:
          - acehelp-yarn-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - acehelp-yarn-deps-{{ .Branch }}
          - acehelp-yarn-deps

      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      # Enable if using yarn
      - run: bin/yarn install

      # Store bundle cache
      - save_cache:
          key: gem-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          key: gem-cache
          paths:
            - vendor/bundle

      # Store yarn cache: When using Yarn
      - save_cache:
          key: acehelp-yarn-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - vendor/node_modules
      - save_cache:
          key: acehelp-yarn-deps-{{ .Branch }}
          paths:
            - vendor/node_modules
      - save_cache:
          key: acehelp-yarn-deps
          paths:
            - vendor/node_modules

      - run: mkdir reports

      # Database setup
      - run: cp config/database.yml.ci config/database.yml
      - run: bundle exec rake db:create db:schema:load --trace
      # Enable if using yarn
      - run: bin/yarn install
      # install elm package
      - run: yarn global add elm --no-progress
      - run: git clone https://github.com/obmarg/libsysconfcpus.git;
      - run: cd libsysconfcpus && ./configure && make && sudo make install && cd ../

      # https://github.com/rails/webpacker/blob/master/docs/troubleshooting.md#running-elm-on-continuous-integration-ci-services-such-as-circleci-codeship-travis-ci
      - run: mv node_modules/.bin/elm node_modules/.bin/elm-old
      - run: printf "#\041/bin/bash\n\necho \"Running elm with sysconfcpus -n 2\"\n\nsysconfcpus -n 2 $CIRCLE_WORKING_DIRECTORY/node_modules/.bin/elm-old \"\$@\"" > node_modules/.bin/elm
      - run: chmod +x node_modules/.bin/elm

      - run: bin/webpack
      - run: bundle exec ruby-audit check
      - run: bundle exec bundle-audit check --update

      # Unit tests
      - run:
          shell: /bin/bash
          command: |
            KNAPSACK_GENERATE_REPORT=true COVERAGE=true bundle exec rake knapsack:minitest --trace

      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
          destination: reports
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_artifacts:
          path: knapsack_minitest_report.json
          destination: knapsack_minitest_report.json


workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
