# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
default: &default
  sidekiq_schedule_file: "config/schedule.yml"


development:
  <<: *default
  secret_key_base: a45a4a7aeb85b46e5413d216702cc26317057694a9a78be9f90ccb4ff747814834e43ae70551f928e21dd38dd501b24646ba33cbf7b273cd289f6dc17954af35
  devise:
    mailer_sender: "'Learn Academy' <do-not-reply@acehelp.com>"
    secret_key: 761c3ac975762d902a566fc89852c55f8dc76ca7d03b0429a3b58fd38a6797db8dc843a38bd4a846b436814b00ed5674cac65cf51f865363568c03f9ffd3e7d6
  mailer:
    perform_deliveries: true
    mailer_delivery_method: smtp
    smtp_settings:
      user_name: <%= ENV["MAILER_USERNAME"] %>
      password: <%= ENV["MAILER_PASSWORD"] %>
      domain: <%= ENV["MAILER_DOMAIN"] %>
      address: <%= ENV["MAILER_ADDRESS"] %>
      authentication: login
      port: 587
      enable_starttls_auto: true
test:
  <<: *default
  secret_key_base: d2100663a73ccdda56bbde92b329a581519cfaec8b9f2cab4b0f00c0ce22e7ae8a0a73c57241f297a6c7b08a41518ec80345b4d858542b0c3c690a2999e2fc3a
  devise:
    mailer_sender: "'Learn Academy' <do-not-reply@acehelp.com>"
    secret_key: 59479ec2879dfa002fd0374b67ad9e3bb3568aa7e723b0b66cc2f9941ac05d7f00c2d8221b3736a6b08c000c6a4c72bc98dc7b328ee50724f885612fa4c7bdb8
  graphql_host: 'http://localhost:3000/graphql_execution/dashboard'
  api_key: 'orgoneapikey'
  mailer:
    perform_deliveries: false
    mailer_delivery_method: :smtp
    smtp_settings:
      user_name: <%= ENV['MAILER_USERNAME'] %>
      password: <%= ENV['MAILER_PASSWORD'] %>
      domain: <%= ENV['MAILER_DOMAIN'] %>
      address: <%= ENV['MAILER_ADDRESS'] %>

staging:
  <<: *default
  store_uploaded_assets_in: aws_s3
  secret_key_base: e66b8d3c84a9a91dbc3fbb78918c0e485789e2d082a998b626ebfee371578841ed88ecdc7f35fb2f1c419c6448ac8cfb958bb60b6babb40ee774331feb674cc8
  devise:
    mailer_sender: "'Learn Academy' <do-not-reply@acehelp.com>"
    secret_key: 0d1067153029e34a519dcf73db39b77504b7c3c856673ff0f361d9c5eeca1cfd28d639692d55d35dda28bc265195a87f3b3e42f4947c8f4c144723a8f0866120
  mailer:
    perform_deliveries: true
    mailer_delivery_method: :smtp
    smtp_settings:
      user_name: <%= ENV['MAILER_USERNAME'] %>
      password: <%= ENV['MAILER_PASSWORD'] %>
      domain: <%= ENV['MAILER_DOMAIN'] %>
      address: <%= ENV['MAILER_ADDRESS'] %>

production:
  <<: *default
  store_uploaded_assets_in: aws_s3
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  devise:
    mailer_sender: "'Learn Academy' <do-not-reply@acehelp.com>"
    secret_key: <%= ENV['DEVISE_KEY'] %>
  mailer:
    perform_deliveries: false
    mailer_delivery_method: :smtp
    smtp_settings:
      user_name: <%= ENV['MAILER_USERNAME'] %>
      password: <%= ENV['MAILER_PASSWORD'] %>
      domain: <%= ENV['MAILER_DOMAIN'] %>
      address: <%= ENV['MAILER_ADDRESS'] %>
